/**
 * SIDCDatawarehouse
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryDTO } from './categoryDTO';
import { ItemUnitOfMeasureDTO } from './itemUnitOfMeasureDTO';
import { ItemUnitOfMeasureGroupDTO } from './itemUnitOfMeasureGroupDTO';
import { SubCategoryDTO } from './subCategoryDTO';
import { SubSubCategoryDTO } from './subSubCategoryDTO';

export interface ItemMasterDataDTO { 
    itemCode?: string;
    itemName?: string;
    categoryId?: number;
    category?: CategoryDTO;
    subCategoryId?: number;
    subCategory?: SubCategoryDTO;
    subSubCategoryId?: number;
    subSubCategory?: SubSubCategoryDTO;
    packagingTypeId?: number;
    isActive?: boolean;
    lastPurchasedDate?: Date;
    itemUnitOfMeasureGroupId?: number;
    itemUnitOfMeasureGroup?: ItemUnitOfMeasureGroupDTO;
    itemUnitOfMeasure?: Array<ItemUnitOfMeasureDTO>;
}