/**
 * SIDCDatawarehouse
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ItemUnitOfMeasureGroupDTO } from './itemUnitOfMeasureGroupDTO';
import { UnitOfMeasureDTO } from './unitOfMeasureDTO';

export interface ItemUnitOfMeasureGroupDetailsDTO { 
    unitOfMeasure?: UnitOfMeasureDTO;
    unitOfMeasureId?: number;
    itemUnitOfMeasureGroupId?: number;
    itemUnitOfMeasureGroup?: ItemUnitOfMeasureGroupDTO;
    alternativeQuantity?: number;
    baseQuantity?: number;
    lineNumber?: number;
    isActive?: boolean;
}